version: '3.8'

services:
  # ---- super-linter ---- #
  lint:
    image: github/super-linter:v3
    volumes:
      - ./:/tmp/lint
    environment:
      RUN_LOCAL: 'true'
      MULTI_STATUS: 'false'
