---
name: Auto Actions

on: # yamllint disable-line rule:truthy
  pull_request_target:
    types: [labeled, unlabeled, synchronize, review_requested, opened, reopened]

jobs:
  auto-approve-github-actions:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]'
    steps:
    - uses: hmarr/auto-approve-action@v2.1.0
      #if: github.event.label.name == 'github_actions'
      if: >-
        contains( github.event.pull_request.labels.*.name, 'github_actions')
        ||
        (
          contains( github.event.pull_request.labels.*.name, 'dependencies')
          &&
          ! contains( github.event.pull_request.labels.*.name, 'core_pulp_modules')
        )
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}

  auto-merge:
    name: Enable automerge on jobs with relevant labels
    runs-on: ubuntu-latest
    steps:
    - uses: alexwilson/enable-github-automerge-action@main
      if: >-
        contains( github.event.pull_request.labels.*.name, 'github_actions')
        ||
        contains( github.event.pull_request.labels.*.name, 'automerge')
        ||
        (
          contains( github.event.pull_request.labels.*.name, 'dependencies')
          &&
          ! contains( github.event.pull_request.labels.*.name, 'core_pulp_modules')
        )
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        merge-method: SQUASH
